// Code generated by entc, DO NOT EDIT.

package ent

import "context"

func (c *Card) Player(ctx context.Context) (*Player, error) {
	result, err := c.Edges.PlayerOrErr()
	if IsNotLoaded(err) {
		result, err = c.QueryPlayer().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (pl *Player) Cards(ctx context.Context) ([]*Card, error) {
	result, err := pl.Edges.CardsOrErr()
	if IsNotLoaded(err) {
		result, err = pl.QueryCards().All(ctx)
	}
	return result, err
}
