// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Card is the predicate function for card builders.
type Card func(*sql.Selector)

// Player is the predicate function for player builders.
type Player func(*sql.Selector)
