// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package api

import (
	"creative-production/ent/card"
)

type CardInput struct {
	PlayerID int       `json:"playerId"`
	Suit     card.Suit `json:"suit"`
	Value    int       `json:"value"`
}

type PlayerInput struct {
	Age  int     `json:"age"`
	Name *string `json:"name"`
}
