name: 'Pull request ready for review'
on:
  pull_request:
    types: [ready_for_review]

jobs:
  pull_request_ready_for_review_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Shuttlerock/actions/actions/pull-request-ready-for-review-action@master
        with:
          credentials-api-prefix: ${{ secrets.CREDENTIALS_API_PREFIX }}
          credentials-api-secret: ${{ secrets.CREDENTIALS_API_SECRET }}
          jira-email:             ${{ secrets.JIRA_EMAIL }}
          jira-host:              ${{ secrets.JIRA_HOST }}
          jira-token:             ${{ secrets.JIRA_TOKEN }}
          organization-name:      ${{ secrets.ORGANIZATION_NAME }}
          repo-token:             ${{ secrets.GITHUB_TOKEN }}
          slack-token:            ${{ secrets.SLACK_TOKEN }}
          write-token:            ${{ secrets.ACTIONS_WRITE_TOKEN }}
