name: 'Trigger action'
on:
  workflow_dispatch:
    inputs:
      email:
        description: 'The email of the user who triggered the action'
        required:    true
      event:
        description: 'The name of the event to trigger'
        required:    true
      param:
        description: 'A string containing a parameter to pass when triggering the event'
        required:    false

jobs:
  trigger_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Shuttlerock/actions/actions/trigger-action@master
        with:
          credentials-api-prefix: ${{ secrets.CREDENTIALS_API_PREFIX }}
          credentials-api-secret: ${{ secrets.CREDENTIALS_API_SECRET }}
          jira-email:             ${{ secrets.JIRA_EMAIL }}
          jira-host:              ${{ secrets.JIRA_HOST }}
          jira-token:             ${{ secrets.JIRA_TOKEN }}
          organization-name:      ${{ secrets.ORGANIZATION_NAME }}
          repo-token:             ${{ secrets.GITHUB_TOKEN }}
          slack-error-channel-id: ${{ secrets.SLACK_ERROR_CHANNEL_ID }}
          slack-token:            ${{ secrets.SLACK_TOKEN }}
          write-token:            ${{ secrets.ACTIONS_WRITE_TOKEN }}
